### ISSUE TITLE
Msstore CLI assumes Flutter project when attempting to init with pubspec.yaml file

### ISSUE THREAD

**Issue by AnalogJ** [microsoft/msstore-cli#27]
Hi!

I'm attempting to publish a pre-generated msix file

I'm calling `msstore init .` with the following pubspec.yaml file:

```yaml
msix_config:
  display_name: Fasten Health
  publisher_display_name: Fasten Health, Inc
  identity_name: FastenHealthInc.FastenHealth
  msix_version: 1.0.8.0
  publisher: CN=94E2XXXX-XXXX-XXXX-XXXX-XXXXXXXXB278
  msstore_appId: 9PLXXXXXXXXP
  store: true
```

which results in the following error:

```
Ok! Found your apps!
This seems to be a Flutter project.
Let's set it up for you!

'flutter pub get' failed
```

I haven't even been able to run my publish command: `msstore publish -v fasten_amd64.msix`
